listener {
    timeout = 300
    on-timeout = brightnessctl -s -q s 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 600
    on-timeout = hyprlock & niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

listener {
    timeout = 1500
    on-timeout = systemctl suspend
    on-resume =
}
